# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ] # Trigger on any tag
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build Linux binary
      run: |
        GOOS=linux GOARCH=amd64 go build -v -o gogs-linux-amd64 .

    - name: Build ARM64 Linux binary
      run: |
        GOOS=linux GOARCH=arm64 go build -v -o gogs-linux-arm64 .

    - name: Build Windows binary
      run: |
        GOOS=windows GOARCH=amd64 go build -v -o gogs-windows-amd64.exe .

    - name: Test
      run: go test -v ./...

    - name: Upload Release Assets
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          gogs-linux-amd64
          gogs-windows-amd64.exe
          gogs-linux-arm64
